Importing Libraries

Assignment DAY - 3

In [1]:
import numpy as np 
import pandas as pd 


# Task 1:- Create a 2D array and multiple each element of the array by 2 and print both old and new array

In [3]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]]) 

In [4]:
arr2 = arr*2

In [7]:
print ("old array: \n", arr)
print ("\new array: \n",arr2)

old array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

ew array: 
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


## Task2:- Create a DataFrame from a dictionary

In [15]:
dc = {"product_name": ["copper", "diamond", "gold", "silver"],
      "price": [1000, 1000000, 10000, 10000],
      "stock_quantity": [10,70,40,30]}

df = pd.DataFrame(dc)

print (f"dataframe:\n{df}")


dataframe:
  product_name    price  stock_quantity
0       copper     1000              10
1      diamond  1000000              70
2         gold    10000              40
3       silver    10000              30


## Task 3 - Data Filtering

In [14]:
filtered_df = df[df["stock_quantity"]>50]
print(f"filtered DataFrame:\n{filtered_df}")

filtered DataFrame:
  product_name    price  stock_quantity
1      diamond  1000000              70
